apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
spec:
  rules:
  - host: echo1.k8s.digitalocean.ck99.io
    http:
      paths:
      - backend:
          service:
            name: echo1
            port: 
              number: 80
  - host: echo2.k8s.digitalocean.ck99.io
    http:
      paths:
      - backend:
          service:
            name: echo2
            port: 
              number: 80
