apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - echo1.k8s.digitalocean.ck99.io
    - echo2.k8s.digitalocean.ck99.io
    secretName: hello-kubernetes-tls
  rules:
    - host: echo1.k8s.digitalocean.ck99.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo1
                port:
                  number: 80
    - host: echo2.k8s.digitalocean.ck99.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo2
                port:
                  number: 80
